# Generated by Django 2.0.10 on 2019-01-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stupidlabelhack',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stupidlabelhack',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_labels',
        ),
        migrations.DeleteModel(
            name='StupidFacilityLabelHack',
        ),
        migrations.DeleteModel(
            name='StupidLabelHack',
        ),
    ]
