# Generated by Django 2.0.10 on 2019-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190126_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_classifier',
            field=models.CharField(blank=True, choices=[('shopmason', 'shopMason Facility')], help_text="Tag this facility to be shown on the ShopMason What's Open sites.", max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='campus_region',
            field=models.CharField(choices=[('front royal', 'Front Royal'), ('prince william', 'Prince William County Science and Technology'), ('fairfax', 'Fairfax'), ('arlington', 'Arlington')], max_length=100),
        ),
    ]
