# Generated by Django 2.0.10 on 2019-01-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190126_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='promote_to_main',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_for_removal',
        ),
    ]
