# Generated by Django 2.0.10 on 2019-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190126_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='urgency_tag',
            field=models.CharField(choices=[('info', 'Advertising / Announcement'), ('minor', 'Expected Hours Change'), ('major', '(Small Scale) Unexpected Hours Change'), ('emergency', '(University Wide) Unexpected Hours Change')], default='Info', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.URLField(verbose_name='Reference URL'),
        ),
    ]
